import * as ts from "typescript";
import { Bundle } from "./Bundle";
import { BundlerOptions } from "./BundlerOptions";
import { BundleBuildResult } from "./BundleBuildResult";
export declare class BundleBuilder {
    private bundle;
    private options;
    private host;
    private program;
    private dependencyTime;
    private dependencyWalkTime;
    private emitTime;
    private buildTime;
    private bundleCodeText;
    private bundleImportText;
    private bundleImportedFiles;
    private bundleModuleImports;
    private bundleSourceFiles;
    constructor(host: ts.CompilerHost, program: ts.Program, bundlerOptions: BundlerOptions);
    build(bundle: Bundle): BundleBuildResult;
    private processModuleContainer;
    private checkModuleInheritance;
    private isInheritedBinding;
    private getImportModuleName;
    private addModuleImport;
    private writeImportDeclaration;
    private processImportExports;
    private whiteOut;
    private emitModuleImportDeclaration;
    private addSourceFileModule;
    private getSymbolFromNode;
    private getNamedBindingsFromImport;
    private reportStatistics;
}
