import { CompileStream } from "../Compiler/CompileStream";
import * as ts from "typescript";
export declare class Project {
    private configFilePath;
    private settings;
    private outputStream;
    private configFileDir;
    private configFileName;
    private totalBuildTime;
    private totalCompileTime;
    private totalPreBuildTime;
    private totalBundleTime;
    private buildContext;
    private configFileWatcher;
    private rebuildTimer;
    constructor(configFilePath: string, settings?: any);
    build(outputStream: CompileStream): ts.ExitStatus;
    private createBuildContext(config);
    private watchProject();
    private completeProjectBuild();
    private buildWorker();
    private parseProjectConfig();
    private onConfigFileChanged;
    private onSourceFileChanged;
    private startRebuildTimer();
    private onRebuildTimeout;
    private readFile(fileName);
    private getSettingsCompilerOptions(jsonSettings, configDirPath);
    private expandFileNames(files, configDirPath);
    private convertProjectFileNames(fileNames, configDirPath);
    private reportBuildStatus(buildStatus);
    private reportStatistics();
}
